from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
import shutil
import subprocess
import sys
import time
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
PYTHON = sys.executable
CODEX_DOCS_DIR = REPO_ROOT / "docs" / "codex"
BENCHMARKS_DIR = CODEX_DOCS_DIR / "benchmarks"
PHASE_A_LATEST_JSON = BENCHMARKS_DIR / "phase_a_latest.json"
PHASE_A_HISTORY_JSONL = BENCHMARKS_DIR / "phase_a_history.jsonl"
PHASE_A_REPORT_MD = CODEX_DOCS_DIR / "ACCEPTANCE_REPORT.md"


def run_step(command: list[str], *, cwd: Path | None = None) -> None:
    location = cwd or REPO_ROOT
    printable = " ".join(command)
    print(f"[quality-gate] Running: {printable} (cwd={location})")
    subprocess.run(command, cwd=location, check=True)


def require_tool(tool_name: str) -> None:
    if shutil.which(tool_name):
        return
    raise SystemExit(
        f"Required tool '{tool_name}' was not found in PATH. "
        f"Install it or skip the profile that depends on it."
    )


def timed_step(name: str, command: list[str], *, cwd: Path | None = None) -> dict:
    started_at = datetime.now(timezone.utc)
    start_perf = time.perf_counter()
    run_step(command, cwd=cwd)
    duration_seconds = round(time.perf_counter() - start_perf, 3)
    return {
        "name": name,
        "command": command,
        "cwd": str((cwd or REPO_ROOT).resolve()),
        "started_at": started_at.isoformat(),
        "duration_seconds": duration_seconds,
    }


def run_python_profile() -> None:
    run_step(
        [
            PYTHON,
            "-m",
            "ruff",
            "check",
            "scripts",
            "tests/test_chunking.py",
            "tests/test_write_json_optimization.py",
        ]
    )
    run_step([PYTHON, "-c", "import lightrag; print(lightrag.__version__)"])
    run_step(
        [
            PYTHON,
            "-m",
            "pytest",
            "tests/test_chunking.py",
            "tests/test_write_json_optimization.py",
            "-m",
            "not integration",
        ]
    )


def run_frontend_profile() -> None:
    require_tool("bun")
    webui_dir = REPO_ROOT / "lightrag_webui"
    run_step(["bun", "install", "--frozen-lockfile"], cwd=webui_dir)
    run_step(["bun", "run", "build"], cwd=webui_dir)


def ensure_benchmark_dirs() -> None:
    BENCHMARKS_DIR.mkdir(parents=True, exist_ok=True)


def read_latest_benchmark() -> dict | None:
    if not PHASE_A_LATEST_JSON.exists():
        return None
    return json.loads(PHASE_A_LATEST_JSON.read_text(encoding="utf-8"))


def write_phase_a_artifacts(result: dict) -> None:
    ensure_benchmark_dirs()
    PHASE_A_LATEST_JSON.write_text(
        json.dumps(result, indent=2) + "\n",
        encoding="utf-8",
    )
    with PHASE_A_HISTORY_JSONL.open("a", encoding="utf-8") as history_file:
        history_file.write(json.dumps(result) + "\n")


def _duration_delta(current: float, previous: float | None) -> str:
    if previous is None:
        return "n/a"
    delta = round(current - previous, 3)
    sign = "+" if delta > 0 else ""
    return f"{sign}{delta:.3f}s"


def write_phase_a_report(result: dict, previous: dict | None) -> None:
    previous_steps = {}
    if previous:
        previous_steps = {
            step["name"]: step["duration_seconds"]
            for step in previous.get("steps", [])
        }

    lines = [
        "# Phase A Acceptance Report",
        "",
        "This report is generated by `python scripts/quality_gate.py --profile phase-a`.",
        "",
        f"- Generated at: `{result['generated_at']}`",
        f"- Git branch: `{result['git']['branch']}`",
        f"- Git commit: `{result['git']['commit']}`",
        f"- Working tree clean for tracked files: `{result['git']['tracked_clean']}`",
        f"- Total duration: `{result['total_duration_seconds']:.3f}s`",
        f"- Previous total duration delta: `{_duration_delta(result['total_duration_seconds'], previous.get('total_duration_seconds') if previous else None)}`",
        "",
        "## Commands",
        "",
    ]

    for step in result["steps"]:
        previous_duration = previous_steps.get(step["name"])
        command = " ".join(step["command"])
        lines.extend(
            [
                f"### {step['name']}",
                f"- Command: `{command}`",
                f"- Working directory: `{step['cwd']}`",
                f"- Duration: `{step['duration_seconds']:.3f}s`",
                f"- Delta vs previous run: `{_duration_delta(step['duration_seconds'], previous_duration)}`",
                "",
            ]
        )

    lines.extend(
        [
            "## Acceptance",
            "",
            "- Phase A benchmark commands are defined and timed.",
            "- Latest benchmark output is stored in `docs/codex/benchmarks/phase_a_latest.json`.",
            "- Historical benchmark output is appended to `docs/codex/benchmarks/phase_a_history.jsonl`.",
            "- This report is the current acceptance note for the optimized Phase A architecture.",
            "",
        ]
    )

    PHASE_A_REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def git_output(command: list[str]) -> str:
    return subprocess.check_output(command, cwd=REPO_ROOT, text=True).strip()


def build_git_metadata() -> dict:
    tracked_clean = not bool(
        git_output(["git", "status", "--short", "--untracked-files=no"])
    )
    return {
        "branch": git_output(["git", "branch", "--show-current"]),
        "commit": git_output(["git", "rev-parse", "HEAD"]),
        "tracked_clean": tracked_clean,
    }


def run_phase_a_profile() -> dict:
    previous = read_latest_benchmark()
    steps = []
    started_at = datetime.now(timezone.utc)
    total_start = time.perf_counter()

    steps.append(
        timed_step(
            "python-ruff",
            [
                PYTHON,
                "-m",
                "ruff",
                "check",
                "scripts",
                "tests/test_chunking.py",
                "tests/test_write_json_optimization.py",
            ],
        )
    )
    steps.append(
        timed_step(
            "python-version",
            [PYTHON, "-c", "import lightrag; print(lightrag.__version__)"],
        )
    )
    steps.append(
        timed_step(
            "python-pytest",
            [
                PYTHON,
                "-m",
                "pytest",
                "tests/test_chunking.py",
                "tests/test_write_json_optimization.py",
                "-m",
                "not integration",
            ],
        )
    )

    require_tool("bun")
    webui_dir = REPO_ROOT / "lightrag_webui"
    steps.append(
        timed_step(
            "frontend-install",
            ["bun", "install", "--frozen-lockfile"],
            cwd=webui_dir,
        )
    )
    steps.append(
        timed_step(
            "frontend-build",
            ["bun", "run", "build"],
            cwd=webui_dir,
        )
    )

    result = {
        "profile": "phase-a",
        "generated_at": started_at.isoformat(),
        "total_duration_seconds": round(time.perf_counter() - total_start, 3),
        "steps": steps,
        "git": build_git_metadata(),
    }
    write_phase_a_artifacts(result)
    write_phase_a_report(result, previous)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run LightRAG quality gates for local development and CI."
    )
    parser.add_argument(
        "--profile",
        choices=("python", "frontend", "phase-a"),
        default="phase-a",
        help="Validation profile to execute.",
    )
    args = parser.parse_args()

    if args.profile == "python":
        run_python_profile()

    if args.profile == "frontend":
        run_frontend_profile()

    if args.profile == "phase-a":
        run_phase_a_profile()

    print(f"[quality-gate] Profile '{args.profile}' completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
